added linting ci requirement

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -33,4 +33,12 @@ jobs:
         run: pip install -r test-requirements.txt
 
       - name: Run Pylint
-        run: pylint TODO_List/**/*.py
+        run: |
+          pylint_output=$(pylint TODO_List/**/*.py)
+          echo "$pylint_output"
+          if [[ "$pylint_output" == *"10.00/10"* ]]; then
+            echo "Pylint check passed"
+          else
+            echo "Pylint check failed"
+            exit 1
+          fi
